name: Build and Deploy OpenHD Image Writer

on:
  push:
    branches:
      - "2.5-evo"
      - "dev-release"
      - "release"
      - "master"
      - "debug"

jobs:
  build-no-container:
    strategy:
      matrix:
        include:
          - distro: focal
            runner: ubuntu-20.04
            container: ""   # Kein Container
          - distro: jammy
            runner: ubuntu-22.04
            container: ""
    runs-on: ${{ matrix.runner }}
    env:
      CLOUDSMITH_RELEASE: ${{ matrix.distro }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update || true
          sudo apt-get upgrade -y || true
          sudo apt-get install -y --no-install-recommends \
            libgnutls28-dev build-essential devscripts debhelper cmake git \
            libarchive-dev libcurl4-openssl-dev qtbase5-dev qtbase5-dev-tools \
            qtdeclarative5-dev libqt5svg5-dev qttools5-dev libssl-dev \
            qml-module-qtquick2 qml-module-qtquick-controls2 \
            qml-module-qtquick-layouts qml-module-qtquick-templates2 \
            qml-module-qtquick-window2 qml-module-qtgraphicaleffects || true
          if [ "${{ matrix.distro }}" = "noble" ]; then
            sudo apt-get install -y python3-pip || true
            pip install cloudsmith-api cloudsmith-cli || true
          fi

      - name: Build package
        run: |
          mkdir build || true
          mv $(ls -A | grep -v "build") build/ || true
          cd build
          debuild -uc -us || true

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: OpenHD-Writer-${{ matrix.distro }}
          path: "*.deb"
          if-no-files-found: warn

      - name: Push to Cloudsmith
        if: (contains(github.ref, 'release') || contains(github.ref, 'master')) && success()
        uses: cloudsmith-io/action@v2
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: push
          format: deb
          owner: openhd
          repo: ${{ github.repository }}
          distro: ubuntu/${{ matrix.distro }}
          file: "*.deb"
          republish: true

  build-container:
    strategy:
      matrix:
        include:
          - distro: lunar
            runner: ubuntu-22.04
            container: "docker://ubuntu:lunar"
          - distro: noble
            runner: ubuntu-22.04
            container: "docker://ubuntu:noble"
    runs-on: ${{ matrix.runner }}
    container:
      image: ${{ matrix.container }}
    env:
      CLOUDSMITH_RELEASE: ${{ matrix.distro }}
    steps:
      - name: Setup environment
        run: |
          apt-get update || true
          apt-get install -y git sudo || true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update || true
          sudo apt-get upgrade -y || true
          sudo apt-get install -y --no-install-recommends \
            libgnutls28-dev build-essential devscripts debhelper cmake git \
            libarchive-dev libcurl4-openssl-dev qtbase5-dev qtbase5-dev-tools \
            qtdeclarative5-dev libqt5svg5-dev qttools5-dev libssl-dev \
            qml-module-qtquick2 qml-module-qtquick-controls2 \
            qml-module-qtquick-layouts qml-module-qtquick-templates2 \
            qml-module-qtquick-window2 qml-module-qtgraphicaleffects || true
          if [ "${{ matrix.distro }}" = "noble" ]; then
            sudo apt-get install -y python3-pip || true
            pip install cloudsmith-api cloudsmith-cli || true
          fi

      - name: Build package
        run: |
          mkdir build || true
          mv $(ls -A | grep -v "build") build/ || true
          cd build
          debuild -uc -us || true

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: OpenHD-Writer-${{ matrix.distro }}
          path: "*.deb"
          if-no-files-found: warn

      - name: Push to Cloudsmith
        if: (contains(github.ref, 'release') || contains(github.ref, 'master')) && success()
        uses: cloudsmith-io/action@v2
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: push
          format: deb
          owner: openhd
          repo: ${{ github.repository }}
          distro: ubuntu/${{ matrix.distro }}
          file: "*.deb"
          republish: true
