# This is a basic workflow to help you get started with Actions

name: OpenHD Image Writer noble

# Controls when the workflow will run
on:
  push:
   branches:
      - "debug"
      - "dev-release"
      - "release"
      - "master"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    container:
      image: docker://ubuntu:noble

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: initialise
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV 
          apt update
          apt install -y git sudo   

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y --no-install-recommends libgnutls28-dev build-essential devscripts debhelper cmake git libarchive-dev libcurl4-openssl-dev qtbase5-dev qtbase5-dev-tools qtdeclarative5-dev libqt5svg5-dev qttools5-dev libssl-dev qml-module-qtquick2 qml-module-qtquick-controls2 qml-module-qtquick-layouts qml-module-qtquick-templates2 qml-module-qtquick-window2 qml-module-qtgraphicaleffects
          sudo apt install -y python3-pip
          pip install cloudsmith-api --break-system-packages
          pip install cloudsmith-cli --break-system-packages
          mkdir build
          mv `ls -A | grep -v "build"` build
          cd build
          debuild -uc -us
          cd ..
          
      - name: Upload to Github
        uses: 'actions/upload-artifact@v4'
        with:
          name: "OpenHD Image Writer"
          path: |
            *.deb
          if-no-files-found: error

      - name: Push
        if: github.ref_name == 'master' || github.ref_name == 'dev-release'
        run: |
          ls -a
          cloudsmith push deb  -k ${{ secrets.CLOUDSMITH_API_KEY }} openhd/release/ubuntu/noble *.deb

