name: OpenHD Image Writer Windows

on:
  push:
    branches:
      - "2.5-evo"
      - "dev-release"
      - "release"
      - "debug"
      - "master"
    paths-ignore:
      - '**.md'
      - '**.asciidoc'
      - '**.adoc'
      - '.gitignore'
      - 'LICENSE'

env:
  BUILD_TYPE: Release
  QT_VERSION: '5.15.2'

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: cmd
        working-directory: src

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          aqtversion: '>=3.1.0'
          host: windows
          target: desktop
          arch: win64_mingw81
          modules: qtbase qtsvg qtquickcontrols2 qttools
          setup-python: true

      - name: Install dependencies
        run: |
          choco install -y nsis openssl
          echo "Qt_DIR=$QT_PATH" >> $GITHUB_ENV
          echo "OPENSSL_ROOT_DIR=C:/Program Files/OpenSSL-Win64" >> $GITHUB_ENV

      - name: Configure CMake
        run: |
          cmake -B build -G "MinGW Makefiles" ^
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} ^
            -DCMAKE_PREFIX_PATH="${{ env.QT_DIR }}/${{ env.QT_VERSION }}/mingw81_64" ^
            -DOPENSSL_ROOT_DIR="${{ env.OPENSSL_ROOT_DIR }}" ^
            -DCMAKE_C_COMPILER=mingw32-gcc.exe ^
            -DCMAKE_CXX_COMPILER=mingw32-g++.exe

      - name: Build project
        run: |
          cmake --build build --config ${{ env.BUILD_TYPE }} --target all -- -j4

      - name: Run windeployqt
        run: |
          cd build
          "${{ env.QT_DIR }}/${{ env.QT_VERSION }}/mingw81_64/bin/windeployqt.exe" OpenHDImageWriter.exe ^
            --no-translations ^
            --qmldir "$GITHUB_WORKSPACE/src" ^
            --compiler-runtime

      - name: Create NSIS installer
        run: |
          cd build
          makensis -DCMAKE_BINARY_DIR="$GITHUB_WORKSPACE/src/build" ^
            -DPROJECT_NAME="OpenHDImageWriter" ^
            -DIMAGER_VERSION_STR="${{ env.IMAGER_VERSION_STR }}" ^
            openhdimagewriter.nsi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenHD-Image-Writer-Windows
          path: |
            src/build/OpenHDImageWriter.exe
            src/build/*.exe
            src/build/*.nsis
          if-no-files-found: error