name: OpenHD Image Writer Windows

on:
  push:
    branches:
      - "2.5-evo"
      - "dev-release"
      - "release"
      - "debug"
    paths-ignore:
      - '**.md'
      - '**.asciidoc'
      - '**.adoc'
      - '.gitignore'
      - 'LICENSE'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        aqtversion: ==3.1.*
        host: windows
        target: desktop
        arch: win32_mingw81
        setup-python: true
        tools: 'tools_cmake'

    - name: Install dependencies
      run: |
        choco install -y nsis openssl.light
        mkdir C:\files
        xcopy "C:\Program Files\OpenSSL" C:\files /E /I /Q
        dir "C:\files"

    # - name: Configure CMake
    #   run: |
    #     cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "Unix Makefiles" -DOPENSSL_ROOT_DIR="C:\files" -DCMAKE_TOOLCHAIN_FILE="C:\Qt\${{env.QT_VERSION}}\${{env.QT_VERSION}}\mingw32\isystem.cmake"

    - name: Build
      run: |
        mkdir -p build
        cd build
        cmake ../
        cmake --build .
        cmake --install .

    - name: Upload to Github  
      uses: actions/upload-artifact@v4
      with:
        name: "OpenHD Image Writer"
        path: '*.exe'
        if-no-files-found: error
