name: OpenHD Image Writer Windows (MinGW + Qt5.15.2)

on:
  push:
    branches:
      - "2.5-evo"
      - "dev-release"
      - "2.0.4"
      - "windows_2"
    paths-ignore:
      - '**/*.md'
      - '**/*.adoc'
      - '.gitignore'
      - 'LICENSE'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v3

      - name: Install Qt
        id: qt-install
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          aqtversion: '==3.1.*'
          host: windows
          target: desktop
          arch: win32_mingw81
          setup-python: false
          tools: tools_cmake

      - name: Show Qt Install Info
        shell: cmd
        run: |
          echo "C:\Qt\Tools\mingw810_32\bin" >> $GITHUB_PATH
          echo "Qt5_DIR: %Qt5_DIR%"
          echo "Contents of Qt5_DIR:"
          dir "%Qt5_DIR%"
          echo "Compiler location:"
          where g++
          echo "CMake version:"
          cmake --version

      - name: Configure CMake
        run: |
          echo "C:\Qt\Tools\mingw810_32\bin" >> $GITHUB_PATH
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles"
          type src/build/CMakeCache.txt


      - name: Check CMakeFiles
        run: |
          dir build
          type build/CMakeCache.txt || true

      - name: Build with Debug Output
        run: |
          echo "C:\Qt\Tools\mingw810_32\bin" >> $GITHUB_PATH
          cd build
          cmake --build .

      - name: List Build Output
        run: |
          dir build
          dir build/bin || echo "No bin directory found"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "OpenHDImageWriter.exe"
          path: src/build/OpenHDImageWriter.exe
          if-no-files-found: error
