name: OpenHD Image Writer Windows

on:
  push:
    branches:
      - "2.5-evo"
      - "dev-release"
      - "release"
      - "debug_older2"
    paths-ignore:
      - '**.md'
      - '**.asciidoc'
      - '**.adoc'
      - '.gitignore'
      - 'LICENSE'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      id: qt-install
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        aqtversion: '==3.1.*'
        host: windows
        target: desktop
        arch: win32_mingw81
        setup-python: false
        tools: tools_cmake tools_mingw81,qt.tools.win32_mingw810
    
    - name: Install OpenSSL via MSYS2
      shell: pwsh
      run: |
          choco install msys2 -y
            Write-Host "Installing OpenSSL headers and libs with pacman..."
            & "C:\tools\msys64\usr\bin\bash.exe" -lc "pacman -Sy --noconfirm mingw-w64-i686-openssl"
            # Sanity check
            if (!(Test-Path "C:\tools\msys64\mingw32\include\openssl\sha.h")) {
              throw "OpenSSL headers not found after pacman install!"
            }     
              
    - name: Install dependencies
      run: |
        choco install nsis --x86 --force -y

    - name: Show Qt Install Info
      run: |
        echo Compiler location:
        where gcc
        where g++
        echo CMake version:
        cmake --version
        dir "D:/a/OpenHD-ImageWriter/OpenHD-ImageWriter"

    - name: Check for OpenSSL headers
      run: |
        dir "C:\tools\msys64\"
        dir "C:\tools\msys64\mingw32\"
        dir "C:\tools\msys64\mingw32\lib\"
        dir "C:\tools\msys64\mingw32\include\openssl\"
      
    - name: Configure CMake
      shell: cmd
      working-directory: src
      run: |
          mkdir build
          cd build
          cmake .. -G "MinGW Makefiles" ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DCMAKE_C_COMPILER="D:/a/OpenHD-ImageWriter/Qt/Tools/mingw810_32/bin/gcc.exe" ^
            -DCMAKE_CXX_COMPILER="D:/a/OpenHD-ImageWriter/Qt/Tools/mingw810_32/bin/g++.exe" ^
            -DOPENSSL_ROOT_DIR="C:/tools/msys64/mingw32" ^
            -DOPENSSL_INCLUDE_DIR="C:/tools/msys64/mingw32/include" ^
            -DOPENSSL_CRYPTO_LIBRARY="C:/tools/msys64/mingw32/lib/libcrypto.dll.a" ^
            -DOPENSSL_SSL_LIBRARY="C:/tools/msys64/mingw32/lib/libssl.dll.a"
    
    - name: Check CMake Cache
      run: |
        dir build
        type build\CMakeCache.txt || echo "Cache missing"

    - name: Build
      shell: pwsh
      run: |
          $env:PATH = "D:/a/OpenHD-ImageWriter/Qt/5.15.2/mingw81_32/bin;D:/a/OpenHD-ImageWriter/Qt/Tools/mingw810_32/bin;" + $env:PATH
          cd build
          cmake --build . --verbose
          dir

    - name: Install NSIS
      run: choco install nsis -y

    - name: Build NSIS Installer
      shell: pwsh
      run: |
        & "C:\Program Files (x86)\NSIS\makensis.exe" "openhdimagewriter.nsi"
      working-directory: src/build


    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: OpenHDImageWriter-Build-Full
        path: C:\a\OpenHD-ImageWriter\OpenHD-ImageWriter\src\build\OpenHD-ImageWriter*
        if-no-files-found: error
