name: OpenHD Image Writer Windows

on:
  push:
    branches:
      - "2.5-evo"
      - "dev-release"
      - "release"
      - "debug_older"
    paths-ignore:
      - '**.md'
      - '**.asciidoc'
      - '**.adoc'
      - '.gitignore'
      - 'LICENSE'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      id: qt-install
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        aqtversion: '==3.1.*'
        host: windows
        target: desktop
        arch: win32_mingw81
        setup-python: false
        tools: tools_cmake tools_mingw81,qt.tools.win32_mingw810
    
    - name: Install OpenSSL from local script
      shell: pwsh
      run: |
          . "$env:GITHUB_WORKSPACE/.github/workflows/ssl.ps1"
      
    - name: Install dependencies
      run: |
        choco install nsis --x86 --force -y

    - name: Show Qt Install Info
      run: |
        echo Compiler location:
        where gcc
        where g++
        echo CMake version:
        cmake --version

    - name: Confirm OpenSSL .dll.a files exist
      run: |
        dir C:\OpenSSL32\lib\MinGW\x86
        xcopy /E /Y /Q C:\OpenSSL32\include D:\a\OpenHD-ImageWriter\Qt\Tools\mingw810_32\include
        xcopy /E /Y /Q C:\OpenSSL32\lib\MinGW\x86\*.dll.a D:\a\OpenHD-ImageWriter\Qt\Tools\mingw810_32\lib

    - name: Configure CMake
      shell: cmd
      run: |
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles" ^
          -DCMAKE_BUILD_TYPE=Release ^
          -DCMAKE_C_COMPILER="D:/a/OpenHD-ImageWriter/Qt/Tools/mingw810_32/bin/gcc.exe" ^
          -DCMAKE_CXX_COMPILER="D:/a/OpenHD-ImageWriter/Qt/Tools/mingw810_32/bin/g++.exe" ^
          -DOPENSSL_ROOT_DIR="C:/OpenSSL32" ^
          -DOPENSSL_INCLUDE_DIR="C:/OpenSSL32/include" ^
          -DOPENSSL_CRYPTO_LIBRARY="C:/OpenSSL32/lib/MinGW/x86/libcrypto.dll.a" ^
          -DOPENSSL_SSL_LIBRARY="C:/OpenSSL32/lib/MinGW/x86/libssl.dll.a"
    
    - name: Check CMake Cache
      run: |
        dir build
        type build\CMakeCache.txt || echo "Cache missing"

    - name: Build
      shell: pwsh
      run: |
          $env:PATH = "D:/a/OpenHD-ImageWriter/Qt/5.15.2/mingw81_32/bin;D:/a/OpenHD-ImageWriter/Qt/Tools/mingw810_32/bin;" + $env:PATH
          cd build
          cmake --build . --verbose
          dir

    - name: Install NSIS
      run: choco install nsis -y

    - name: Build NSIS Installer
      run: |
        "C:\Program Files (x86)\NSIS\makensis.exe" openhdimagewriter.nsi
      working-directory: src/build


    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: OpenHDImageWriter-Build-Full
        path: C:\a\OpenHD-ImageWriter\OpenHD-ImageWriter\src\build\OpenHD-ImageWriter*
        if-no-files-found: error
      