name: OpenHD Image Writer Windows

on:
  push:
    branches:
      - "2.5-evo"
      - "dev-release"
      - "2.0.4"
      - "windows_2"
    paths-ignore:
      - '**.md'
      - '**.asciidoc'
      - '**.adoc'
      - '.gitignore'
      - 'LICENSE'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt (MinGW)
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        aqtversion: ==3.1.*
        host: windows
        target: desktop
        arch: win32_mingw81
        tools: 'tools_cmake'

    - name: Install MSYS2 for MinGW make
      run: |
        choco install -y msys2
        echo "C:\tools\msys64\usr\bin" >> $GITHUB_PATH
        echo "C:\tools\msys64\mingw32\bin" >> $GITHUB_PATH

    - name: Build
      run: |
        mkdir -p build
        cd build
        cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
        mingw32-make

    - name: Upload to Github  
      uses: actions/upload-artifact@v4
      with:
        name: "OpenHD Image Writer"
        path: src/build/OpenHDImageWriter.exe
        if-no-files-found: error
